# This is a basic workflow to help you get started with Actions

name: 'CI Pipeline'

# Triggers the workflow on push or pull request events
on: [push, pull_request]

#on:
#  push:
#    branches:
#    - main
#  pull_request:

jobs:
  e2e-tests:
    name: 'Playwright Tests'
    runs-on: windows-latest # or macos-latest, ubuntu-latest

    env:
      working-directory: ./src/tests

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1

      - name: Playwright Setup
        uses: microsoft/playwright-github-action@v1

      - name: Install Dependencies
        run: npm install

      - name: Run Playwright Tests
        run: npm run test
        timeout-minutes: 15
        env:
          BROWSER: 'chromium'
          HEADLESS: false
          CI: true

      - name: Publish Test Artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: 'test-artifacts'
          path: artifacts/**/*.*

      - name: Publish .xml Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: always()
        with:
          files: artifacts/testResults/**/*.xml
          check_name: 'Playwright Test Results'
